export const APP_WRITE_ID = '65abb1a4da73c4df529a'
export const DB_ID = 'crm-db'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
